### ISSUE TITLE
Slackリンクについて

### ISSUE THREAD

**Issue by Hiro222st** [SSL-Roots/Roots_home#5]
SSL Slackの招待リンクが切れています。参加したいのですがどうすればいいでしょうか？

**Comment by tilt-silvie** [comment]
@Hiro222st 報告ありがとうございます。HPのほうは後ほど修正しておきます。
ひとまず、以下の招待リンクから参加いただけるかと思います。
https://join.slack.com/t/robocup-ssl-japan/shared_invite/zt-1vlx1enoi-yrRg3b4TESQn2d16xfBLeg

**Comment by tilt-silvie** [comment]
HPの方も更新しました。

**Comment by tilt-silvie** [comment]
対応完了しましたのでクローズします。
@Hiro222st 報告ありがとうございました！
