### ISSUE TITLE
MFT2024での御礼_RumiCar

### ISSUE THREAD

**Issue by Rumika685** [SSL-Roots/Roots_home#8]
お世話になっております。
RumiCarの千葉です。

先日はMFT2024で名刺交換し、お話ししてくださりありがとうございました。

RumiCarでは誰でも自動運転の開発を簡単にできるのを目指しています。
RumiCarによって自動運転が実現した後も、ユーザーが自動運転車を好きなようにカスタマイズできるのも目指しています。

昨年と今年もトヨタ技術会さんにRumiCarを50セット購入いただき、トヨタ技術会の方が豊田市の小学生向けに半年間講座を開催しました。
また、通信技術の企業にもRumiCarを購入いただき、自動運転に必要な通信技術を開発されています。
このように、小学生の方から企業の方までRumiCarを使用していただいています。

こちらはRumiCarのSNSのメディアのリンク集です。https://linktr.ee/RumiCar
RumiCarのプログラム、車体の組み立て方やなどはGitHubに公開されています。
もしRumiCar Facebook groupへのご参加がまだでしたら、是非ご参加ください。
こちらで質問や自動運転に関するディスカッションを自由にできます。
YouTubeチャンネルにはRumiCarに限らず自動運転のイベントや試乗の動画もあるので、是非ご覧ください。

RumiCarと何かコラボできそうなことがあれば是非ご一緒したいと思います。
また、何かRumiCarでお手伝いできることがあればお声がけください。
今後ともよろしくお願いいたします。

**Comment by ShotaAk** [comment]
MFTで展示を見ていただき、ありがとうございました。

「技術的な開発活動を簡単にする」という点で、私たちの取り組みと共通する部分があり、とても印象的です。
今後もよろしくお願いします。
